[package]
name = "async-global-executor"
version = "0.2.2"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description =  "A global executor built on top of async-executor and async-io"
edition = "2018"
license = "MIT"
repository = "https://github.com/Keruspe/async-global-executor"
homepage = "https://github.com/Keruspe/async-global-executor"
documentation = "https://docs.rs/async-global-executor"
keywords = ["async", "await", "future", "executor"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-channel = "^1.4"
async-executor = "^0.2"
async-io = "^0.2"
futures-lite = "^1.0"
num_cpus = "^1.13"
once_cell = "^1.4"

[dev-dependencies]
doc-comment = "^0.3"
