[package]
name = "async-global-executor"
version = "1.3.0"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description =  "A global executor built on top of async-executor and async-io"
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Keruspe/async-global-executor"
homepage = "https://github.com/Keruspe/async-global-executor"
documentation = "https://docs.rs/async-global-executor"
keywords = ["async", "await", "future", "executor"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[features]
default = ["async-io"]
tokio02 = ["async-compat"]
tokio03 = ["tokio03-crate"]

[dependencies]
async-executor = "^1.3"
futures-lite = "^1.0"
num_cpus = "^1.13"
once_cell = "^1.4"

[dependencies.async-compat]
version = "^0.1"
optional = true

[dependencies.async-io]
version = "^1.0"
optional = true

[dependencies.tokio03-crate]
package = "tokio"
version = "^0.3"
optional = true
default-features = false
features = ["rt"]

[dev-dependencies.tokio02-crate]
package = "tokio"
version = "^0.2"
default-features = false
features = ["rt-core"]

[dev-dependencies]
doc-comment = "^0.3"
